name: Publish to pub.dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Check flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      # Here you can insert custom steps you need
      # - run: dart tool/generate-code.dart

      - name: Re-generate the translations
        run: ./scripts/regenerate-translations.sh
      
      
      # This is needed in order for the authentication to success
      # dart pub token add https://pub.dev --env-var PUB_TOKEN
      # Requests to "https://pub.dev" will now be authenticated using the secret token stored in the environment variable "PUB_TOKEN".
      - uses: dart-lang/setup-dart@v1
      # - name: Update the authorization requests to "https://pub.dev" to use the environment variable "PUB_TOKEN".
      #   run: dart pub token add https://pub.dev --env-var PUB_TOKEN

      - name: Publish
        run: flutter pub publish --force
